name: oStaff
version: 2.0
main: rip.orbit.ostaff.oStaff
load: STARTUP
author: Alfie, Branched

commands:
  editstaff:
  togglestaff:
    aliases:
      - hidestaff
      - showstaff
  vanish:
    aliases:
      - v
  staffmode:
    aliases:
      - mod
      - modmode
      - staff
      - h